
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin:
            - 'https://ai-language-reader-frontend.vercel.app/'

        allow_headers:
            - Content-Type
            - Authorization

        allow_methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS

        max_age: 3600

    paths:
        '^/':
            origin_regex: false
